name: Generate js.cool

on:
  push:
    branches: source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Fetch events
        run: |-
          sudo timedatectl set-timezone Asia/Shanghai
          npm install
          npm run generate
      - name: Commit and push
        run: |-
          git config --global user.email "i@js.cool" && git config --global user.name "Github Bot"
          cd dist
          git init
          git add . && git commit -m ":memo: Auto Generate" || exit 0
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/js-cool/js-cool.github.io.git" master:master
          git push --force "https://${{ secrets.CODING_TOKEN  }}@e.coding.net/willin/js-cool/js-cool.github.io.git" master:master
